### ISSUE TITLE
Is this work?

### ISSUE THREAD

**Issue by Vadim2S** [dong03/MVSS-Net#10]
I am have my own small test image corpus. I am run this project. And... Result is around a ZERO! Casia or Defacto - no changes. May be MVSS work only with special cases? For example (original, fake, map, map on fake) and ignore text, please:

![MVSS-Net_girl](https://user-images.githubusercontent.com/84853762/140720893-7759e73b-c5e7-47a6-be1f-b8b9e84844b2.png)
![MVSS-Net_bird_background](https://user-images.githubusercontent.com/84853762/140721121-4a43eae9-db44-4798-b95c-8b603fc02cd6.png)

**Comment by dong03** [comment]
Well, it suggests detecting manipulations under real scenarios is challenging. It requires generalizability.

BTW, I have some questions.
1) For Fig2 (with bird), which part is considered to be manipulated, left or right?  You see, if the right is, MVSS at least hit sth.
(I have a more interesting one, from left to right, fake_img, ground truth, output
![image](https://user-images.githubusercontent.com/32919661/140852431-0ff00a3f-8732-4e8f-83df-531cd75944df.png)

2) How about other sota works? You may find their github repos in our paper.

One more thing, recently we are carrying experiments on IMD2020(Imd2020: A large-scale
annotated dataset tailored for detecting manipulated images). It contains 2k wild ps photos collected from the Internet. MVSS along with other sota works all get mean pixel-F1 lower than 0.3  (about the level of Fig2 if the right is considered to be manipulated).

(This area has not achieved silver bullet under real scenarios.

**Comment by Vadim2S** [comment]
1) Bird and bird home is original. Blured green background naturally produced from mirror camera. Castle tower background is fake. It is right answer "bird AND bird home is fake" also, But "only bird" is false positive. Neverless it is just fun example.

More bold and undetected fakes (original, fake, map, map+fake)

1.1) Gun removed

![MVSS-Net_gun](https://user-images.githubusercontent.com/84853762/141106321-80716232-ce72-4fa6-a846-bcddae9b6577.png)
:

2.2) Bottle inserted

![MVSS-Net_man_bottle](https://user-images.githubusercontent.com/84853762/141106400-35beb828-1de1-450a-b2b8-5b0280bc94cd.png)

2) Thank for hint, I am see other sota works later.
