### ISSUE TITLE
Could not find the TianChi Model

### ISSUE THREAD

**Issue by garyhsu29** [dong03/MVSS-Net#18]
In the Readme it said:
Update: 22.02.17, Pretrained model for [Real-World Image Foregery Localization Challange](https://tianchi.aliyun.com/competition/entrance/531945/introduction)
But I could not find the model anywhere, could you please help me on that? Thank you!

**Comment by dong03** [comment]
It goes right here.
![微信图片_20220612153326](https://user-images.githubusercontent.com/32919661/173222477-3f4e2d72-3e50-425e-ab49-adbed6de148d.png)
