### ISSUE TITLE
MVSS-Net++ Pretrained Weight

### ISSUE THREAD

**Issue by nadifray** [dong03/MVSS-Net#27]
Hello, thank you for your works

can i ask for the pretrained weight of mvss-net++ to be uploaded in google drive too?

Thank you in advance

**Comment by dong03** [comment]
Please check here:  https://drive.google.com/drive/folders/19bR99yN8Qgfrs--eiV7dV5cCgr4ZKcYN?usp=sharing

**Comment by kostino** [comment]
Is the code for MVSS-net++ or the training code going to be available?
Thank you!

**Comment by kostino** [comment]
Specifically there seems to be a non-trainable layer between the ReLU activation and the 1x1 Conv in the ConvGEM module based on the checkpoint you shared. Could you maybe share what this layer is?
