### ISSUE TITLE
WRONG metrics implementation when calculating the image level F1 score!

### ISSUE THREAD

**Issue by SunnyHaze** [dong03/MVSS-Net#30]
There is a severe error when calculating the image level F1 score. This question can be exactly found here: 
https://github.com/dong03/MVSS-Net/blob/cc2aed77a823723015f95e4a6a3e344f3ddb7ccc/common/utils.py#L44-L45 

The correct metric would be `F1 = 2 * true_pos / (2 * true_pos + false_pos + false_neg + eps)`, where eps is a numerical stability factor. 

Or calculate with the Recall in the coming formula instead of the Specificity:
![image](https://user-images.githubusercontent.com/62173481/232842178-7fc2797e-0c11-48ef-bf51-4fb5062d40c6.png)
![image](https://user-images.githubusercontent.com/62173481/232842306-ae1530b2-6afe-47ee-98c2-cc989942540f.png)

And your implementation for pixel level F1 score is correct, you could refer to this part of the codes:
https://github.com/dong03/MVSS-Net/blob/cc2aed77a823723015f95e4a6a3e344f3ddb7ccc/common/utils.py#L57-L59

I hope you can recalculate and revise the metrics of the image level F1 score results, and at least publish a patch Table of metrics on GitHub, otherwise, it will be **very unfair** for future research, as this calculation will bring higher results to your F1 score values.

To create a better research environment, we hope that you can value research integrity! Thank you very much for your inspiring work!!

**Comment by kostino** [comment]
Adding on to the points made by @SunnyHaze:
Concretely the difference between the computed metric lies here:
![f1mistake](https://user-images.githubusercontent.com/27733299/232899105-9c93a634-b752-47d5-8bee-cbcc0bf542dc.png)
As we can see depending on the distributions in the datasets that we experiment on the reported result can be way off the true value of F1. Especially in real-world scenarios where naturally TN >> TP this will produce a value significantly higher than the true F1 value

**Comment by Chenxr1999** [comment]
> There is a severe error when calculating the image level F1 score. This question can be exactly found here:
> 
> https://github.com/dong03/MVSS-Net/blob/cc2aed77a823723015f95e4a6a3e344f3ddb7ccc/common/utils.py#L44-L45
> 
> The correct metric would be `F1 = 2 * true_pos / (2 * true_pos + false_pos + false_neg + eps)`, where eps is a numerical stability factor.
> 
> Or calculate with the Recall in the coming formula instead of the Specificity: ![image](https://user-images.githubusercontent.com/62173481/232842178-7fc2797e-0c11-48ef-bf51-4fb5062d40c6.png) ![image](https://user-images.githubusercontent.com/62173481/232842306-ae1530b2-6afe-47ee-98c2-cc989942540f.png)
> 
> And your implementation for pixel level F1 score is correct, you could refer to this part of the codes:
> 
> https://github.com/dong03/MVSS-Net/blob/cc2aed77a823723015f95e4a6a3e344f3ddb7ccc/common/utils.py#L57-L59
> 
> I hope you can recalculate and revise the metrics of the image level F1 score results, and at least publish a patch Table of metrics on GitHub, otherwise, it will be **very unfair** for future research, as this calculation will bring higher results to your F1 score values.
> 
> To create a better research environment, we hope that you can value research integrity! Thank you very much for your inspiring work!!

As stated in Section 4.1 of the paper, 

> For the pixel-level manipulation detection, following previous works, we compute pixel-level precision and recall, and report their F1. For image-level manipulation detection, in order to measure the miss detection rate and false alarm rate, **we report sensitivity, specifificity and their F1**. 

For pixel-level evaluation, in order to compare with previous works, we calculate F1 using the harmonic average of precision and recall. **For image-level evaluation, F1 is calculated as the harmonic average of sensitivity and specificity**, since sensitivity and specificity are not affected by the distribution of positive and negative samples in the test data, so a more reliable evaluation conclusion can be obtained.

**Comment by SunnyHaze** [comment]
Thank you for your reply!

>we report sensitivity, specificity and their F1.

F1 score is a specialized term used to refer to the harmonic mean of the precision and recall([WIKIPIDIA](https://en.wikipedia.org/wiki/F-score)).  The “F1” in the above sentence is almost impossible for most readers to consider it as the harmonic mean of **sensitivity and specificity**, if they have received a good mathematical education. The better choice should be described as "the harmonic mean of sensitivity and specificity".

You said this is a more reliable conclusion but did not clarify the source of this particular value and attempt to confuse it. However, if this false high indicator cannot be clearly pointed out, it will cause considerable trouble for subsequent Image Manipulation Detection reviewers, making it difficult to truly evaluate the current SOTA model. Because they only glance at the result of Image-level classification table and say, 'This is the result of that ordinary F1 score.'.

I hope you can seriously consider this issue and maintain academic honesty, and I will further investigate this matter.

**Comment by li-xirong** [comment]
this is not an issue and has nothing to do with academic honesty. Case closed.

**Comment by SunnyHaze** [comment]
6

**Comment by erliufashi** [comment]
In fact, the harmonic average between sensitivity and specificity should not be used at all, but rather the average value directly, which has a special name [Balanced accuracy (BA)](https://en.wikipedia.org/wiki/F-score)
